### PR TITLE
Create gui

### PR DESCRIPTION
**Pull request by Zach10a**
# Creation of a very basic GUI

## Motivation
Allows greater usability and is useful for those not as technically gifted with python. I am putting this PR in now so that others may help out if they so desire and the final product can be discussed.

## Relevant Issues
I intended to create a package installer for this. I will be creating the package installer in a different PR as it is a little big for one feature branch.

## Changes
Created a GUI

## New Dependencies
PyInstaller >= 5.0.0 in requirements_dev.txt
PySide2~=5.15.2.1 in requirements.txt

## Change Magnitude
Not release-worthy yet, however once this and the package installer have been merged it will require a release.

### CODE REVIEW

**Comment by Zach10a** [comment]
Travis CI is not working due to issues with Qt. Recommend the following https://stackoverflow.com/questions/56826665/travis-ci-failing-to-build-due-to-pyside2-and-matplotlib

**Comment by camUrban** [comment]
Hey @Zach10a! Thanks for this awesome pull request and all the hard work you've put in. I apologize for the radio silence these last few days; things have been pretty crazy at work. I should be able to review your request tomorrow and we can move forward with getting it merged!

**Comment by Zach10a** [comment]
Fixes #18

**Comment by Zach10a** [comment]
Hi @camUrban, hope you're doing alright and work isn't too manic. Absolutely not a priority but just a bump in case you've not seen this pop up anywhere. I intend to leave it how it is and not clutter up the commits to fix the Travis CI and fix it in a branch afterwards. I also have the package branch pretty much good to go other than some troubleshooting!

**Comment by camUrban** [comment]
Hey man! I'm so sorry again about the delay. I'm in the final two weeks of my current job, so I'm working overtime to wrap up several projects. I feel bad because I know how much time you've put into this, but I think I'll need to delay reviewing this request until after I finish. However, on Monday, 8/1, the first thing I'll do is work on this merge! I hope that's okay, and again, thank you so much for all the effort on your part!

**Comment by camUrban** [comment]
Hey @Zach10a, I hope you survived the hot weather unscathed! I'm now finished up with work and am ready to start helping with this! Here are my initial thoughts:
- I made two small commits to make the dependency versions slightly more restrictive.
- I noticed that the Travis CI testing is still failing. I wonder if we should remove the GUI from the CI testing now? Could that be done by removing line 16 from the new `.travis.yml` file? What are your thoughts?
- I'm a bit confused by the `pterasoftware/models` Python package. Some of the files seem to be the same as those in the `examples` folder, but others define a new class. Are the copies from `examples` work with the GUI yet?
- We should probably have a docstring for main.py. Even a one-liner such as `"""This script opens the GUI to demonstrate Ptera Software analyzing example models."""` would be okay. :smile:

**Comment by Zach10a** [comment]
Hi Cam,

Just out of contact until the 12th Aug, will have a look at these changes when I am back.

Glad you're well

**Comment by Zach10a** [comment]
Hi Cam, had an hour out so have had a look.

- Added that line to main.py. It's a bit of a filler but I will write docs for it later on.
- `pterasoftware/models` is a framework to enable customisation at a later date. I've kept it in to avoid having to write it all again, however the current examples do just action the scripts in the `examples` folder.
- Unsure on the Travis CI thing. If I'm honest it all appears to work from my end for all tests, however I will keep looking at fixes to allow it to work. Failing that I will use our lord and master _StackOverflow_.

All of those should be actioned in the next few commits. I'll be in and out of comms for the next week or so, will get back to you on any comments as soon as I can!

**Comment by Zach10a** [comment]
Ok so I've gone a little further than I should have on this branch, but it saves you having to look at more PRs. We now have a fully-fledged installer and build instructions that can install the program to the user's computer with no use of the command line. It can show all examples through the help folder. If you're happy with this being V1.0.0 (that is what I've designated it atm) then the installer .exe can be appended to the release section on the front page alongside the source code.

Looking forward to moving on with other aspects of the project!

**Comment by Zach10a** [comment]
@camUrban any movement on this?

**Comment by Zach10a** [comment]
Hey @camUrban, would there be any way to resolve this?

**Comment by camUrban** [comment]
Hi @Zach10a. So sorry about the long wait on this. I've been in my first semester of grad school and have been struggling to find the time to work on this. This is my last week of classes. I'll take another look on Monday, 12/12, which is my first day of winter break. Thanks for all the work and your patience.

**Comment by Zach10a** [comment]
No worries dude! Hope you're enjoying, have a good Christmas period.

**Comment by camUrban** [comment]
I just merged the pull request. Great job, and thank you again! I will close this thread, but I may open a new issue in the next few days as I start prepping a new major version release with your contributions.

**Comment by camUrban** [comment]
I just merged the pull request. Great job, and thank you again! I will close this thread, but I may open a new issue in the next few days as I start prepping a new major version release with your contributions.

**Pull request merged**
